import glob
import pandas as pd
import os

# copy syntax:
# if classify is True,
#   copy png files from ../data/train-1/job* directories to
#       either images1/classifications/accepted or
#       images1/classifications/rejected
# else //classification is false
#   copy png files from ../data/test/job* directories to images/test
#

def cp_png_unclassified(src, dst):
    #copy test files. no classification
    os.system('cp '+ src+'/*.png'+' '+dst)

def cp_png_classified(src, dst):

    selection_filename = src + '/' + os.path.basename(src) + '-selection.csv'
    selection = pd.read_csv(selection_filename, sep=',')
    selection = selection.drop(selection.columns[0], 1)
    selection = selection.as_matrix()

    pics = glob.glob(src+'/'+'*.png')
    total_images = len(pics)

    i = 0
    for pic in pics:

        # find the class
        start = pic.find('-classes-') + len('-classes-')
        if pic.find('_') == -1:
            #not a file generated by augmentation
            end = pic.find('.png')
        else:
            #file generted by keras augmentation. introduces _x_ into the file name
            end = pic.find('_')

        class_num = int(pic[start:end:])
        if selection[class_num-1] == 1:
            #accepted; copy to the accepted directory
            os.system('cp '+pic+' '+dst+'/accepted/')
        else:
            if selection[class_num-1] == 0:
                #rejected: copy to the rejected directiry
                os.system('cp ' + pic + ' ' + dst + '/rejected/')
            else:
                print ('Houston, we have a problem!!!')


def cp_png_to_tl(src, dst, classify):
    #Traverse the directory for csv files and png files
    for dirName, subdirList, fileList in os.walk(src):
        for subdir in subdirList:
            if classify:
                cp_png_classified(dirName+'/'+subdir, dst)
            else:
                cp_png_unclassified(dirName+'/'+subdir, dst)

if __name__ == '__main__':

    from_dir = os.getcwd()+'/../data/train-1'
    to_dir = os.getcwd() + '/images1/classifications/'
    cp_png_to_tl(from_dir, to_dir, True)

    from_dir = os.getcwd()+'/../data/test-1'
    to_dir = os.getcwd() + '/images1/test'
    cp_png_to_tl(from_dir, to_dir, False)



